import AppMetaDataProvider from '@/providers/AppMetaDataProvider';
import { ProgressBarProvider } from '@/providers/ProgressBarProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark group' data-locator-target='vscode'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppMetaDataProvider />
        <ProgressBarProvider>{children}</ProgressBarProvider>
      </body>
    </html>
  );
}
