export enum PET_ENUM {
  BLACK_CAT = 'BLACK_CAT',
  GREY_CAT = 'GREY_CAT',
  HAPPY_DOG = 'HAPPY_DOG',
  ORANGE_CAT = 'ORANGE_CAT',
  WHITE_PUPPY = 'WHITE_PUPPY',
  SNOOPY = 'SNOOPY',
  LAZY_CAT = 'LAZY_CAT',
}
